name: Security and Dependency Scanning

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run security scan daily at 2 AM UTC
    - cron: '0 2 * * *'

jobs:
  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: |
          backend/package-lock.json
          
    - name: Install dependencies
      run: |
        cd backend
        npm ci
        
    - name: Run npm audit
      run: |
        cd backend
        npm audit --audit-level=moderate
        
    - name: Run npm audit fix (dry run)
      run: |
        cd backend
        npm audit fix --dry-run
        
  dependency-check:
    name: Dependency Check
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: |
          backend/package-lock.json
          
    - name: Install dependencies
      run: |
        cd backend
        npm ci
        
    - name: Check for outdated packages
      run: |
        cd backend
        npm outdated || true
        
    - name: Check for unused dependencies
      run: |
        cd backend
        npx depcheck || true
